apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-restart-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-restart-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: deployment-restart-account
  namespace: default
roleRef:
  kind: Role
  name: deployment-restart-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deployment-restart-account
          containers:
          - name: kubectl-container
            image: bitnami/kubectl
            command: ["kubectl", "rollout", "restart", "deployment/github-copilot-demo"]
          restartPolicy: OnFailure
